### ISSUE TITLE
email parser matches header date as well as body date

### ISSUE THREAD

**Issue by skaliak** [skaliak/dt520#21]
the header date causes a failed match, so the pattern needs to be tuned, or the first match attempt need to be skipped somehow.
```
procmail: Notified comsat: "lindberp@:/nfs/stak/students/l/lindberp/python /nfs/stak/students/l/lindberp/dt520/sas_procmail_filter.py"
From lindberp@engr.orst.edu Wed Feb 11 11:30:52 2015
 Subject: Advising Signup with McGrath, D Kevin confirmed for Smith, John
  Folder: python /nfs/stak/students/l/lindberp/dt520/sas_procmail_filt      833
Traceback (most recent call last):
  File "/nfs/stak/students/l/lindberp/dt520/sas_procmail_filter.py", line 50, in <module>
    main()
  File "/nfs/stak/students/l/lindberp/dt520/sas_procmail_filter.py", line 41, in main
    appointment_data = parse_appointment_email(input_txt)
  File "/nfs/stak/students/l/lindberp/dt520/email_parser.py", line 79, in parse_appointment_email
    result['start'], result['end'] = _parse_start_end(*datetime_args)
  File "/nfs/stak/students/l/lindberp/dt520/email_parser.py", line 43, in _parse_start_end
    month, day, year = re.match('[A-Za-z]+, ([A-Za-z]+) (\d{1,2}).., (\d{4})', date).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by skaliak** [comment]
This is pretty open and shut, so I don't think it really needs review... Just wanted to document it, though.
